routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/







use App\Http\Controllers\CourseController;
use App\Http\Controllers\LabController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\ProductController;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

require __DIR__ . '/auth.php';
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::get('/', [ProductController::class, 'index'])->name('product.index');
// Route::prefix('product')->group(function () {
//     Route::get('/create', [ProductController::class, 'create'])->name('product.create');
//     Route::post('/store', [ProductController::class, 'store'])->name('product.store');
//     Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('product.edit');
//     Route::patch('/update/{id}', [ProductController::class, 'update'])->name('product.update');
//     Route::get('/delete/{id}', [ProductController::class, 'destroy'])->name('product.delete');
// });
Route::resource('product',ProductController::class);
// student..........................
Route::prefix('student')->group(function () {
    Route::get('/create', [StudentController::class, 'create'])->name('student.create');
    Route::post('/store', [StudentController::class, 'store'])->name('student.store');
    Route::get('/index', [StudentController::class, 'index'])->name('student.index');
    Route::get('/edit/{id}', [StudentController::class, 'edit'])->name('student.edit');
    Route::patch('/update/{id}', [StudentController::class, 'update'])->name('student.update');
    Route::get('/delete/{id}', [StudentController::class, 'destroy'])->name('student.delete');
});
// course...................
Route::prefix('course')->group(function () {
    Route::get('/create', [CourseController::class, 'create'])->name('course.create');
    Route::post('/store', [CourseController::class, 'store'])->name('course.store');
    Route::get('/index', [CourseController::class, 'index'])->name('course.index');
    Route::get('/edit/{id}', [CourseController::class, 'edit'])->name('course.edit');
    Route::patch('/update/{id}', [CourseController::class, 'update'])->name('course.update');
    Route::get('/delete/{id}', [CourseController::class, 'destroy'])->name('course.delete');
});
// patiend.......................
Route::prefix('patient')->group(function () {
    Route::get('/create', [PatientController::class, 'create'])->name('patient.create');
    Route::post('/store', [PatientController::class, 'store'])->name('patient.store');
    Route::get('/index', [PatientController::class, 'index'])->name('patient.index');
    Route::get('/edit/{id}', [PatientController::class, 'edit'])->name('patient.edit');
    Route::patch('/update/{id}', [PatientController::class, 'update'])->name('patient.update');
    Route::get('/delete/{id}', [PatientController::class, 'destroy'])->name('patient.delete');
});
// lab...................
Route::prefix('lab')->group(function () {
    Route::get('/create', [LabController::class, 'create'])->name('lab.create');
    Route::post('/store', [LabController::class, 'store'])->name('lab.store');
    Route::get('/index', [LabController::class, 'index'])->name('lab.index');
    Route::get('/edit/{id}', [LabController::class, 'edit'])->name('lab.edit');
    Route::patch('/update/{id}', [LabController::class, 'update'])->name('lab.update');
    Route::get('/delete/{id}', [LabController::class, 'destroy'])->name('lab.delete');
});
// order..............

Route::prefix('order')->group(function () {
    Route::get('/index', [OrderController::class, 'index'])->name('order.index');
    Route::get('/create', [OrderController::class, 'create'])->name('order.create');
    Route::post('/store', [OrderController::class, 'store'])->name('order.store');
    Route::get('/edit/{id}', [OrderController::class, 'edit'])->name('order.edit');
    Route::patch('/update/{id}', [OrderController::class, 'update'])->name('order.update');
    Route::get('/delete/{id}', [OrderController::class, 'destroy'])->name('order.delete');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $fillable = ['name', 'title', 'category', 'is_active','price', 'description','image'];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\Product;
use Illuminate\Http\Request;
use Image;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $product = Product::all();
        return view('products.index', compact('product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
       // dd($request);
        Product::create([
            'name' => $request->name,
            'title' => $request->title,
            'category' => $request->category,
            'price'=>$request->price,
            'is_active' => $request->is_active? True :False,
            'description' => $request->description,
            'image' => $this->uploadimage($request->file('image'))
        ]);
        return redirect()->route('product.index')->with('success', 'SuccessFully Created Product');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        return view('products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, $id)
    {
        $products = Product::find($id);
        $requestData = [
            'name' => $request->name,
            'title' => $request->title,
            'category' => $request->category,
            'price'=>$request->price,
            'is_active' => $request->is_active ? true : false,
            'description' => $request->description,
            
        ];

        if ($request->hasFile('image')) {
            $requestData['image'] = $this->uploadImage($request->file('image'));

            // dd($requestData['image']);
        }
        $products->update($requestData);
        return redirect()->route('product.index')->with('success', 'products edit Successdfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        $product->delete();
        return redirect()->route('product.index')->with('success', 'successfully delete');
    }

    public function uploadImage($image)
    {
        $originalName = $image->getClientOriginalName();
        $fileName = date('YmdHi') . time() . $originalName;
        // $image->move(storage_path ('/app/public/Products'),
        //  $filename);
        Image::make($image)
            ->resize(200, 200)
            ->save(storage_path() . '/app/public/products/' . $fileName);

        return $fileName;
    }
}

resources/views/products/create.blade.php
<x-master>
    <div class="col-md-8 px-2 mx-3">
        <div class="card">
            <div class="card-body">
                <h5 class="text-center text-light p-3 bg-dark">Create Product</h5>
                <form action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <x-form.input type="text" name="name" label="Name Of Product" class="text-dark" placeholder="Name Of product" />

                    <x-form.input type="text" name="title" label="Title" class="text-dark" placeholder="Product Title" />

                    <x-form.select name="category" label="Select category" :values="[
                            'T-Shirt' => 'T-Shirt',
                             'Jeans' => 'Jeans',
                            'Glasses' => 'Glasses',
                            
                 ]" />
                   
                 <x-form.input type="number" name="price" label="Price" class="text-dark" placeholder="Name Of product" />

                 <x-form.checkbox  type="checkbox" name="is_active"  :checklist="['Is Active']" lable="Is Active :" id="pre-checked-2" value="1" />

                 <x-form.textarea name="description" label="Description" class="text-dark" placeholder="Write Here ............." />

                 <x-form.input type="file" name="image" label="Picture"   />
                    <button type="submit" class="btn btn-success">Resister Now</button>
                </form>
            </div>
        </div>
</x-master>

resources/views/products/edit.blade.php
<x-master>
    <div class="col-md-8 px-2 mx-3">
        <div class="card">
            <div class="card-body">
                <form action="{{ route('product.update', $product->id) }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('patch')
                    <x-form.input type="text" name="name" label="Name Of Product" value="{{old('name',$product->name)}}" class="text-dark" placeholder="Name Of product" />

                    <x-form.input type="text" name="title" label="Title"  value="{{old('name',$product->title)}}" class="text-dark" placeholder="Product Title" />


                  
                    <x-form.select name="category" label="Select category" :values="[
                            'T-Shirt' => 'T-Shirt',
                             'Jeans' => 'Jeans',
                            'Glasses' => 'Glasses',
                            
                 ]" :selectedValue="$product->category"/>

                 <x-form.input type="number" name="price" label="Price"  value="{{old('price',$product->price)}}" class="text-dark" placeholder="Product Title" />

                   
                 @php
            
            if($product->is_active){
                $checkedItems=[0];
            }
            else {
                $checkedItems=[];
            }
            @endphp
                 <x-form.checkbox  type="checkbox" name="is_active"  :checklist="['Is Active']" :checkedItems="$checkedItems" lable="Is Active :" id="pre-checked-2" value="1" />

                 <x-form.textarea name="description" label="Description" value="{{old('description',$product->description)}}" class="text-dark" placeholder="Write Here ............." />

                 <x-form.input type="file" name="image" label="Picture"   />

                    <button type="submit" class="btn btn-success">Submit Now</button>
                </form>
            </div>
        </div>
</x-master>

resources/views/products/index.blade.php
<x-master>
    <div class="col-md-8 px-2 mx-3">
        <div class="card">
            <a href="{{ route('product.create') }}"> <button class="btn btn-danger">Add a Product</button></a>
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Name</th>
                            <th scope="col">Title</th>
                            <th scope="col">Category</th>
                            <th scope="col">Price</th>
                            <th scope="col">Is_active</th>
                            <th scope="col">Description</th>
                            <th scope="col">Image</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($product as $products)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{ $products->name }}</td>
                            <td>{{ $products->title }}</td>
                            <td>{{ $products->category }}</td>
                            <td>{{ $products->price }}</td>
                            <td>{{ $products->is_active == 1 ? 'Active' : 'Disable' }}</td>
                            <td>{{ $products->description }}</td>

                            <td><img src="{{asset('storage/products/'
                            .$products->image)}}" height="50" alt="no image"></td>


                            <td>
                                <a href="{{ route('product.edit', $products->id) }}"><button class="btn btn-info">Edit</button></a>
                                {{-- <a href="{{ route('product.delete', $products->id) }}"><button type="submit" class="btn btn-danger">
                                        Delete </button></a> --}}
                                <form action="{{ route('product.destroy', $products->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button class="btn btn-sm btn-outline-danger">Delete </button>
                                </form>
                            </td>

                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</x-master>